### ISSUE TITLE
Question: SaaS (multy tenancy) module based on AdminRestrictBranch

### ISSUE THREAD

**Issue by spoetnik** [adrianbj/AdminRestrictBranch#5]
I am looking for a way to restrict access to content based on a 'TenantID', or a shared branch.
 A 'TenantID' on the User-template, and a 'TenantID' on all restricted templates.

Then hook into all Processwire CRUD-operations, to filter only content with the User's TenantID or something.

Would this module be a good starting point? Doe you have suggestions how to get started? Do you see any pitfalls?

Thanks

**Comment by adrianbj** [comment]
@spoetnik - it doesn't sound like this module suits your needs. It is all about restricting users to a single branch of the page tree - great if you have a site with multiple clients that need to manage their specific sections of the site. Typically each of these sections uses the same template / page structure, although this isn't necessary.

It sounds like you have specific templates you need to restrict access to so you should hook into the various Page::edit etc permissions that you need to restrict and check the `TenantID` to determine access. You might find some code in this module helpful it figuring out how to do this thougj.

**Comment by adrianbj** [comment]
I am going to close this, but please ask any additional questions if you have them.
